#! /bin/sh
python main.py ./datas ./results/logistics_PdmmISVR --epochs 10 --batch_size 100 --l2_lambda 0.01 --model_name logistics --dataset_name fashion --group_channels 32 --drop_rate 0.1 --last_drop_rate 0.5 --loglevel INFO --train_data_length 10000 --cuda_device_no 0 --skip_plots --scheduler StepLR --step_size 410 --gamma 0.9 --sleep_factor 0 PdmmISVR node0 ./conf/node_list.n8.doublering.round8.json ./conf/hosts.n8.json --lr 0.002 --swap_timeout 10 --async_step > ./results/logistics_PdmmISVR/node0.txt 2>&1 &
python main.py ./datas ./results/logistics_PdmmISVR --epochs 10 --batch_size 100 --l2_lambda 0.01 --model_name logistics --dataset_name fashion --group_channels 32 --drop_rate 0.1 --last_drop_rate 0.5 --loglevel INFO --train_data_length 10000 --cuda_device_no 1 --skip_plots --scheduler StepLR --step_size 410 --gamma 0.9 --sleep_factor 0 PdmmISVR node1 ./conf/node_list.n8.doublering.round8.json ./conf/hosts.n8.json --lr 0.002 --swap_timeout 10 --async_step > ./results/logistics_PdmmISVR/node1.txt 2>&1 &
python main.py ./datas ./results/logistics_PdmmISVR --epochs 10 --batch_size 100 --l2_lambda 0.01 --model_name logistics --dataset_name fashion --group_channels 32 --drop_rate 0.1 --last_drop_rate 0.5 --loglevel INFO --train_data_length 10000 --cuda_device_no 2 --skip_plots --scheduler StepLR --step_size 410 --gamma 0.9 --sleep_factor 0 PdmmISVR node2 ./conf/node_list.n8.doublering.round8.json ./conf/hosts.n8.json --lr 0.002 --swap_timeout 10 --async_step > ./results/logistics_PdmmISVR/node2.txt 2>&1 &
python main.py ./datas ./results/logistics_PdmmISVR --epochs 10 --batch_size 100 --l2_lambda 0.01 --model_name logistics --dataset_name fashion --group_channels 32 --drop_rate 0.1 --last_drop_rate 0.5 --loglevel INFO --train_data_length 10000 --cuda_device_no 3 --skip_plots --scheduler StepLR --step_size 410 --gamma 0.9 --sleep_factor 0 PdmmISVR node3 ./conf/node_list.n8.doublering.round8.json ./conf/hosts.n8.json --lr 0.002 --swap_timeout 10 --async_step > ./results/logistics_PdmmISVR/node3.txt 2>&1 &
python main.py ./datas ./results/logistics_PdmmISVR --epochs 10 --batch_size 100 --l2_lambda 0.01 --model_name logistics --dataset_name fashion --group_channels 32 --drop_rate 0.1 --last_drop_rate 0.5 --loglevel INFO --train_data_length 10000 --cuda_device_no 4 --skip_plots --scheduler StepLR --step_size 410 --gamma 0.9 --sleep_factor 0 PdmmISVR node4 ./conf/node_list.n8.doublering.round8.json ./conf/hosts.n8.json --lr 0.002 --swap_timeout 10 --async_step > ./results/logistics_PdmmISVR/node4.txt 2>&1 &
python main.py ./datas ./results/logistics_PdmmISVR --epochs 10 --batch_size 100 --l2_lambda 0.01 --model_name logistics --dataset_name fashion --group_channels 32 --drop_rate 0.1 --last_drop_rate 0.5 --loglevel INFO --train_data_length 10000 --cuda_device_no 5 --skip_plots --scheduler StepLR --step_size 410 --gamma 0.9 --sleep_factor 0 PdmmISVR node5 ./conf/node_list.n8.doublering.round8.json ./conf/hosts.n8.json --lr 0.002 --swap_timeout 10 --async_step > ./results/logistics_PdmmISVR/node5.txt 2>&1 &
python main.py ./datas ./results/logistics_PdmmISVR --epochs 10 --batch_size 100 --l2_lambda 0.01 --model_name logistics --dataset_name fashion --group_channels 32 --drop_rate 0.1 --last_drop_rate 0.5 --loglevel INFO --train_data_length 10000 --cuda_device_no 6 --skip_plots --scheduler StepLR --step_size 410 --gamma 0.9 --sleep_factor 0 PdmmISVR node6 ./conf/node_list.n8.doublering.round8.json ./conf/hosts.n8.json --lr 0.002 --swap_timeout 10 --async_step > ./results/logistics_PdmmISVR/node6.txt 2>&1 &
python main.py ./datas ./results/logistics_PdmmISVR --epochs 10 --batch_size 100 --l2_lambda 0.01 --model_name logistics --dataset_name fashion --group_channels 32 --drop_rate 0.1 --last_drop_rate 0.5 --loglevel INFO --train_data_length 10000 --cuda_device_no 7 --skip_plots --scheduler StepLR --step_size 410 --gamma 0.9 --sleep_factor 0 PdmmISVR node7 ./conf/node_list.n8.doublering.round8.json ./conf/hosts.n8.json --lr 0.002 --swap_timeout 10 --async_step > ./results/logistics_PdmmISVR/node7.txt 2>&1 &
